const TRAVEL = {
    FETCH: "TRAVEL_FETCH",
    FETCH_ERROR: "TRAVEL_FETCH_ERROR",
    FETCH_SUCCESS: "TRAVEL_FETCH_SUCCESS"
};

const PLANT = {
    FETCH: "PLANT_FETCH",
    FETCH_ERROR: "PLANT_FETCH_ERROR",
    FETCH_SUCCESS: "PLANT_FETCH_SUCCESS"
};

const ACCOUNT = {
    FETCH: "ACCOUNT_FETCH",
    FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
    FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
    FETCH_LOGUOUT_SUCCESS: "ACCOUNT_FETCH_LOGOUT_SUCCESS"
};

export { TRAVEL, PLANT, ACCOUNT };