const TRAVEL = {
    FETCH: "TRAVEL_FETCH",
    FETCH_ERROR: "TRAVEL_FETCH_ERROR",
    FETCH_SUCCESS: "TRAVEL_FETCH_SUCCESS"
};

const PLANT = {
    FETCH: "PLANT_FETCH",
    FETCH_ERROR: "PLANT_FETCH_ERROR",
    FETCH_SUCCESS: "PLANT_FETCH_SUCCESS"
}

export { TRAVEL, PLANT };